# Application settings
defaultTableCount: 4

# Technical server configuration
server:
  type: simple
  applicationContextPath: /api
  adminContextPath: /admin
  connector:
    type: http
    port: 8000
